### PR TITLE
Remove Bukkit.getOfflinePlayers()

### PR DESCRIPTION
**Pull request by okx-code**
This makes up for 2.25% of a tick, on average, on the latest spark report.

### CODE REVIEW

**Comment by psygate** [comment]
This changes the semantics of completion for commands and may not be intended. OfflinePlayer will not be autocompleted by name anymore for all commands that reference this code. Use an external list to preserve behaviour and circumvent bukkit api costs instead may be a better idea.

**Comment by okx-code** [comment]
Yeah it could use a cache but it's not really worth it given it's just autocomplete

**Comment by psygate** [comment]
Atleast this command will suffer from this change as far as I can tell. And I think the expected behaviour of inviting players is to also auto complete offline players for namelayer groups. It would be confusing for players like me to have offline players not show up from the completion of possible invitations.

https://github.com/CivMC/NameLayer/blob/master/paper/src/main/java/vg/civcraft/mc/namelayer/command/commands/InvitePlayer.java

**Comment by okx-code** [comment]
As it stands it is pretty easy to lag the server without this PR, so if you want to to that then feel free

**Comment by psygate** [comment]
Do you want me to PR your branch / repo or this one?

**Pull request merged**
