### PR TITLE
Fix: reinforcements are not saving into the database each minute

### PR DESCRIPTION
**Pull request by Aleksey-Terzi**

### CODE REVIEW

**Comment by Maxopoly** [comment]
This seems incorrect, if a chunk was loaded and then unloaded, it would still have a timestamp larger than 0. Race conditions during chunk (un-)loading need to be taken care of. Also careful with that method, iirc it's logic was specifically built around the methods using it and its name is not entirely descriptive of what its supposed to check.

**Comment by Maxopoly** [comment]
Ok yeah, the logic should be like:

```java

	public boolean isChunkLoaded() {
		if (this.lastUnloadingTime > 0) {
			return this.lastUnloadingTime < this.lastLoadingTime;
		} else {
			return this.lastLoadingTime > 0;
		}
	}
```

**Comment by Aleksey-Terzi** [comment]
> Ok yeah, the logic should be like:

Yes, agree, this improves it.

The change is tested and works as expected.

**Comment by Aleksey-Terzi** [comment]
>  its name is not entirely descriptive of what its supposed to check.

What about the name isActive?
Though in this case fields lastUnloadingTime and lastLoadingTime should be renamed too.

Also, I think the context where this function is used, it is pretty descriptive.

**Comment by Aleksey-Terzi** [comment]
> Also, I think in the context where this function is used, it is pretty descriptive.

I mean the current name, i.e. isChunkLoaded, is descriptive and no need to change it.

**Comment by Maxopoly** [comment]
Actually yeah, you're right, the name is fine.

**Review by Maxopoly — APPROVED** [review]

**Pull request merged**
